[[edge_functions]]
  function = "hello"
  path = "/public/index.html"

[[redirects]]
  from = "public/img/*"
  to = "public/img/:splat"
  status = 200

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
